---
- name: Determine the timestamp for the backup.
  set_fact:
    now: '{{ lookup("pipe", "date +%F-%T") }}'

- name: Create a directory for a database backup to live.
  file:
    path: '{{ backup_dir.rstrip("/") }}/{{ now }}/'
    mode: 0775
    owner: root
    state: directory
  notify: Remove the backup directory.

- name: Get tower database settings
  shell: "tower-manage print_settings | grep '^DATABASES'"
  register: results
  changed_when: False

- name: Ingest tower database settings
  set_fact:
    tower_db_settings: "{{ results.stdout | regex_replace('DATABASES\\s+= ', '') }}"

